DROP TABLE IF EXISTS UserDevices;
DROP TABLE IF EXISTS UserPreferences;

DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS TheatreMovies;

DROP TABLE IF EXISTS MoviePreferences;
DROP TABLE IF EXISTS FoodPreferences;
DROP TABLE IF EXISTS RestaurantFoods;
DROP TABLE IF EXISTS RestaurantLocations;
DROP TABLE IF EXISTS LocationPreferences;
DROP TABLE IF EXISTS Houses;
DROP TABLE IF EXISTS Theatres;

DROP TABLE IF EXISTS Devices;
DROP TABLE IF EXISTS Preferences;
DROP TABLE IF EXISTS Movies;
DROP TABLE IF EXISTS Foods;
DROP TABLE IF EXISTS Restaurants;
DROP TABLE IF EXISTS Locations;
